### ISSUE TITLE
Dot-file config is hella confusing

### ISSUE THREAD

**Issue by mstade** [pemrouz/popper#7]
This is nit-picking level 1000 for sure, but the dot in `.popper.yml` had me thrown off for a while, thinking the config reader was broken. It wasn't until I read the Popper source that I saw the dot. In general, convention seems to be that dot-files don't have extensions. It's the wild west for sure when it comes to whether config files should be dot-files or not; I don't care much either way. It's nice that tool config files get out of the way when you ls I suppose, but that's about the only benefit I can think of. Regardless, I'd suggest drop the prefix (or support both with and without in loading the config) or drop the dot.

**Comment by pemrouz** [comment]
Ah, interesting note. I didn't think too much about this, just followed things like `.travis.yml`. I don't mind changing this, or making it read either..
